### ISSUE TITLE
Does not provide an export named 'execa' after install

### ISSUE THREAD

**Issue by richard-edwards** [harlan-zw/nuxt-seo#217] opened 2024-04-03 14:37 UTC
### Describe the bug

I removed nuxt-og-image from my project and installed nuxt-seo, set up the module in nuxt.config.ts etc and now I'm getting this on run dev:

```
gpp-web:dev: [10:14:28 a.m.]  ERROR  [worker reload] [worker init] The requested module 'file:///home/richard/Projects/golfpro/node_modules/.pnpm/execa@5.1.1/node_modules/execa/index.js' does not provide an export named 'execa'
gpp-web:dev: 
gpp-web:dev:   import { execa } from '/home/richard/Projects/golfpro/node_modules/.pnpm/execa@5.1.1/node_modules/execa/index.js';
gpp-web:dev:   ^^^^^
gpp-web:dev:   SyntaxError: The requested module '/home/richard/Projects/golfpro/node_modules/.pnpm/execa@5.1.1/node_modules/execa/index.js' does not provide an export named 'execa'
gpp-web:dev:   at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
gpp-web:dev:   at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
gpp-web:dev: 
```

### System / Nuxt Info

```Shell
------------------------------
- Operating System: Linux
- Node Version:     v18.18.2
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.15.4
- Builder:          -
- User Config:      debug, site, vite, build, watch, typescript, extends, modules, components, ui, fontMetrics, googleFonts, imports, app, runtimeConfig, supabase, dayjs, devtools
- Runtime Modules:  @nuxtjs/supabase@1.1.7, @pinia/nuxt@0.5.1, @nuxt/content@2.12.1, @nuxt/image@1.4.0, @nuxt/ui, @nuxtjs/fontaine@0.4.1, @nuxtjs/google-fonts@3.1.3, @vueuse/nuxt@10.9.0, @vue-email/nuxt@0.8.19, dayjs-nuxt@2.1.9, @nuxtjs/seo@2.0.0-rc.10
- Build Modules:    -
------------------------------
```

**Comment by harlan-zw** [comment] 2024-04-04 01:28
The problem is that one of your dependencies has locked `execa` to an earlier version, all of the Nuxt internals use v8.

You can debug it by running `pnpm why execa` and finding what is keeping it at `5.1.1`

**Comment by richard-edwards** [comment] 2024-04-04 11:27
Thanks. Looks like it was `eslint-plugin-prettier-vue` but I was already using the latest so no way for me to upgrade it. I'm wondering if I can pin execa to v8 somehow. Looks like some other packages like `unocss` and  `@unocss/preset-icons` also use it but if I remove just `eslint-plugin-prettier-vue` I have no error now.

**Comment by harlan-zw** [comment] 2024-04-07 01:25
Yes pinning it _should_ work although may break the eslint plugin, I'd recommend using https://github.com/nuxt/eslint. Nothing else I can do on my end so going to close this.

**Closed by harlan-zw** 2024-04-07 01:25 UTC
