### ISSUE TITLE
useFuse: Upgrade fuse.js to v7

### ISSUE THREAD

**Issue by patriciorivera** [harlan-zw/nuxt-seo#267] opened 2024-07-09 18:04 UTC
### Describe the bug

Having this error at deploy:

[2024-07-09 17:43:23] │ npm ERR! code EUSAGE
[2024-07-09 17:43:23] │ npm ERR! 
[2024-07-09 17:43:23] │ npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
[2024-07-09 17:43:23] │ npm ERR! 
[2024-07-09 17:43:23] │ npm ERR! Invalid: lock file's fuse.js@7.0.0 does not satisfy fuse.js@6.6.2
[2024-07-09 17:43:23] │ npm ERR! Missing: fuse.js@7.0.0 from lock file

doing a search:

PS C:\Users\patri\node\00_dabble\frontend\dabble-frontend-market> npm ls fuse.js
npm ERR! code ELSPROBLEMS
npm ERR! invalid: fuse.js@7.0.0 C:\Users\patri\node\00_dabble\frontend\dabble-frontend-market\node_modules\fuse.js
nuxt-app@ C:\Users\patri\node\00_dabble\frontend\dabble-frontend-market
└─┬ @nuxtjs/seo@2.0.0-rc.11
  ├─┬ @nuxtjs/sitemap@5.3.2
  │ └─┬ @nuxt/devtools-ui-kit@1.3.9
  │   └─┬ @vueuse/integrations@10.11.0
  │     └── fuse.js@7.0.0 deduped invalid: "^6" from node_modules/@vueuse/integrations
  └─┬ nuxt-link-checker@3.0.0-rc.12
    └── fuse.js@7.0.0

related with this: https://github.com/vueuse/vueuse/pull/4036

Regards,
P

### System / Nuxt Info

```Shell
nuxt 3.12.3
node 20.9.0
npm 10.1.1
```

**Comment by harlan-zw** [comment] 2024-07-11 02:56
The issue is that Nuxt SEO uses Fuse.js v7 but `@nuxt/devtools-ui-kit` is using VueUse which is using v6. Once VueUse v11 is available and being used by Nuxt Devtools then this would be solved.

I'd suggest adding an override or something for the time being

**Comment by harlan-zw** [comment] 2024-07-25 10:08
I'm going to close this for now as there's nothing I can do on my end, please open an issue with [@nuxt/devtools-ui-kit](https://github.com/nuxt/devtools) or manually provide an override.

**Closed by harlan-zw** 2024-07-25 10:08 UTC

**Comment by patriciorivera** [comment] 2024-07-25 15:36
I agree Harlan, and thank you very much for the work on this project.

Regards,
P
