### ISSUE TITLE
Automatic Image Discovery not working

### ISSUE THREAD

**Issue by michael-picard** [harlan-zw/nuxt-seo#301] opened 2024-08-22 06:36 UTC
### Describe the bug

My site is generated with Nuxt content. Despite the page content being inside a `main` tag the sitemap shows zero image when there is one.

<img width="477" alt="Screenshot 2024-08-22 at 08 35 23" src="https://github.com/user-attachments/assets/7094ac80-860c-4270-900a-6eac5281635f">
<img width="569" alt="Screenshot 2024-08-22 at 08 35 40" src="https://github.com/user-attachments/assets/19a66ef9-ab3c-4282-b449-c186f8448a19">

### Reproduction

https://stackblitz.com/~/github.com/michael-picard/cv-2024?file=README.md&initialPath=/blog/languages/php/php-weakmap

### System / Nuxt Info

```Shell
- Operating System: `Darwin`
- Node Version:     `v22.0.0`
- Nuxt Version:     `3.12.4`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `npm@10.5.1`
- Builder:          `-`
- User Config:      `future`, `devtools`, `site`, `build`, `modules`, `content`, `vite`, `app`, `nitro`, `sitemap`, `compatibilityDate`
- Runtime Modules:  `()`, `nuxt-particles@0.3.0`, `@nuxt/image@1.7.0`, `@nuxt/content@2.13.2`, `@nuxtjs/sitemap@6.0.0-beta.4`
- Build Modules:    `-`
```

**Comment by just-h** [comment] 2024-08-22 11:50
Same issue here, worth noting it only appears to happen with images generated by the nuxt/image module, at least for me.

**Comment by harlan-zw** [comment] 2024-08-22 14:51
Hi, there's a fix for this in the latest beta. If you still have issues please provide a [minimal reproduction](https://stackblitz.com/edit/nuxt-starter-a5qk3s?file=nuxt.config.ts).

**Comment by Aravinda93** [comment] 2024-08-28 18:41
@just-h @michael-picard 
I am also facing the same issue with `Nuxt/Content`. Have you guys found any workaround or alternative approach for this? I am also following up on this and posted here: https://github.com/harlan-zw/nuxt-seo/issues/298

Due to this issue, my production deployment has been blocked so wanted to see if I can figure out a work-around until we have a final fix.

**Comment by Aravinda93** [comment] 2024-08-29 08:46
> Same issue here, worth noting it only appears to happen with images generated by the nuxt/image module, at least for me.

I guess its works for both Nuxt images and normal images because in my case I tried with both and both seem to fail to generate for images: https://github.com/harlan-zw/nuxt-seo/issues/298

**Comment by Aravinda93** [comment] 2024-08-29 08:46
> Same issue here, worth noting it only appears to happen with images generated by the nuxt/image module, at least for me.

@just-h 

I guess its works for both Nuxt images and normal images because in my case I tried with both and both seem to fail to generate for images: https://github.com/harlan-zw/nuxt-seo/issues/298

**Comment by harlan-zw** [comment] 2024-08-30 03:57
I've tested with 6.0.0-rc.4 and it appears to be working correctly, please upgrade.

![image](https://github.com/user-attachments/assets/b4897fc7-24c3-41be-8e83-5c3fb2b6238e)

**Closed by harlan-zw** 2024-08-30 03:57 UTC

**Comment by just-h** [comment] 2024-08-31 04:43
@michael-picard @Aravinda93 Manually adding 6.0.0-beta.5 of the sitemap module fixed it for me.
As of right now the lastest nuxt-seo module itself still loads the beta.2 of the sitemap as a dependency, where the issue appears to be present for my stack, so adding the sitemap module separately seems to be a functioning workaround.

**Comment by Aravinda93** [comment] 2024-08-31 08:20
@just-h 

Thanks a lot for the response. So I have used the `6.0.0-beta.5` and using the `ssr:true` in my `nuxt.config.js` as per the [reply here](https://github.com/harlan-zw/nuxt-seo/issues/298#issuecomment-2320127538).

Please once let me know how to fix the issue. Because with `ssr:false` I do not get any of the issues during `nuxt generate`. Following is my code in the [CodeSandBox](https://codesandbox.io/p/devbox/sharp-hill-fx62n5?file=%2Fnuxt.config.js). [Generated SiteMap.xml](https://codesandbox.io/p/devbox/sharp-hill-fx62n5?file=%2F.output%2Fpublic%2F__sitemap__%2Fen.xml)

But with `ssr:true` when I run the `nuxt generate or npm run generate` then I get a lot of the errors for some reason. If I use `ssr:false` then it works fine without issues but `sitmap.xml` does not include images and other things.

Also, I have few `tags` in my `.md` files and if the `tags` have spaces then the spaces are retained in the generated URL within the `sitemap.xml ` file. Can you please let me know how to fix this?

I have a Nuxt content website with some of the markdown files in /content/index.md with tags such as:
```
    navigation:
    linkTitle: "Introduction"
    tags : ["Testing tools", "performance tests", "process automation", "supply chain management", "load tests"]
    
```

I am generating the `sitemap.xml ` using the `nuxtjs/sitemap with ssr:true ` during the generation of the sitemap it generates the URL with spaces suchas:

```
       <url>
        <loc>http://localhost:3000/tags/performance tests</loc>
        <xhtml:link rel="alternate" href="http://localhost:3000/tags/performance tests" hreflang="x-default" />
        <xhtml:link rel="alternate" href="http://localhost:3000/tags/performance tests" hreflang="en" />
    </url>
```

Since it generates the URL with spaces they are invalid but URLs are valid when I navigate to them then they are present with spaces:
```
http://localhost:3000/tags/performance%20tests
```

How to ensure the sitemap adds appropriate spaces and checks for valid URLs before generating the `sitemap.xml ` using Nuxt Sitemap and replaces the spaces with URL-safe characters.

**Comment by Aravinda93** [comment] 2024-08-31 17:23
> @michael-picard @Aravinda93 Manually adding 6.0.0-beta.5 of the sitemap module fixed it for me. As of right now the lastest nuxt-seo module itself still loads the beta.2 of the sitemap as a dependency, where the issue appears to be present for my stack, so adding the sitemap module separately seems to be a functioning workaround.

@just-h 

Thanks a lot its working fine now with `ssr:true` and able to get the images in `sitemap.xml` file. But I am facing one small issue:

I have a few `tags` in my `.md` files; if the `tags` have spaces, then the spaces are retained in the generated URL within the `sitemap.xml ` file. Can you please let me know how to fix this?

I have a Nuxt content website with some of the markdown files in /content/index.md with tags such as:
```
  navigation:
  linkTitle: "Introduction"
  tags : ["Testing tools", "performance tests", "process automation", "supply chain management", "load tests"]
    
```

I am generating the `sitemap.xml ` using the `nuxtjs/sitemap with ssr:true ` during the generation of the sitemap it generates the URL with spaces such as:

```
 <url>
    <loc>http://localhost:3000/tags/performance tests</loc>
    <xhtml:link rel="alternate" href="http://localhost:3000/tags/performance tests" hreflang="x-default" />
    <xhtml:link rel="alternate" href="http://localhost:3000/tags/performance tests" hreflang="en" />
</url>
```

Since it generates the URL with spaces they are invalid but URLs are valid when I navigate to them then they are present with spaces:
```
http://localhost:3000/tags/performance%20tests
```

How to ensure the sitemap adds appropriate spaces and checks for valid URLs before generating the `sitemap.xml ` using Nuxt Sitemap and replacing the spaces with URL-safe characters.
